# Generated by Django 2.1.7 on 2019-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20190506_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='user_lang',
            field=models.CharField(blank=True, max_length=50, verbose_name='user language'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='user_url',
            field=models.URLField(blank=True, unique=True, verbose_name='user url'),
        ),
    ]
