# Generated by Django 2.1.7 on 2019-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20190507_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='user_url',
            field=models.URLField(unique=True, verbose_name='user url'),
        ),
    ]
