# Generated by Django 2.1.7 on 2019-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20190507_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='user_url',
            field=models.URLField(verbose_name='user url'),
        ),
    ]
