# Generated by Django 2.1.7 on 2019-05-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_auto_20190507_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='user_url',
        ),
    ]
