# Generated by Django 2.1.7 on 2019-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_remove_shopuserprofile_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='user_url',
            field=models.URLField(blank=True, unique=True, verbose_name='user url'),
        ),
    ]
