# Generated by Django 2.1.7 on 2019-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20190507_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='userpic_url',
            field=models.URLField(blank=True, verbose_name='userpic url'),
        ),
    ]
