# Generated by Django 2.1.7 on 2019-05-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_shopuserprofile_userpic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='userpic_url',
        ),
    ]
